apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-sa
  namespace: train-orchestrator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestrator-role
  namespace: train-orchestrator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get","list","watch","create","update","patch","delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator-rb
  namespace: train-orchestrator
subjects:
  - kind: ServiceAccount
    name: orchestrator-sa
    namespace: train-orchestrator
roleRef:
  kind: Role
  name: orchestrator-role
  apiGroup: rbac.authorization.k8s.io
